meta:
  version: 1.0.0
config-sparse:
  modules:
    exe-value-patcher:
      config:
        config_file:
          contents:
            value: ucp/modules/exe-value-patcher-*/values.yml
  plugins: {}
  load-order: []
